/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.78
 * Generated at: 2023-12-06 22:47:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import mx.com.cursodia.javaEE2022.Beans.Videojuego;
import mx.com.cursodia.javaEE2022.Beans.Proveedor;
import java.sql.ResultSet;
import java.sql.SQLException;

public final class MostrarVideojuegos_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("mx.com.cursodia.javaEE2022.Beans.Videojuego");
    _jspx_imports_classes.add("mx.com.cursodia.javaEE2022.Beans.Proveedor");
    _jspx_imports_classes.add("java.sql.SQLException");
    _jspx_imports_classes.add("java.sql.ResultSet");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta charset=\"UTF-8\">\r\n");
      out.write("		<title>Lista de Videojuegos</title>\r\n");
      out.write("		<link rel=stylesheet href=\"css/mostrarVideojuegos.css\" type=\"text/css\">\r\n");
      out.write("		<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\r\n");
      out.write("	</head>\r\n");
      out.write("	<body>\r\n");
      out.write("		<!-- Imports -->\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("	        <br>\r\n");
      out.write("	        <div class=\"d-flex justify-content-between mt-3\">\r\n");
      out.write("	        	<h3>Lista de Videojuegos</h3>\r\n");
      out.write("	        	<div>\r\n");
      out.write("			        <a class=\"btn btn-secondary\" href=\"FormularioInsertarVideojuego.jsp\" role=\"button\"> Agregar Videojuego </a>\r\n");
      out.write("			        <!-- <a class=\"btn btn-secondary\" href=\"MostrarProveedores.do\" role=\"button\"> Proveedores </a>-->\r\n");
      out.write("	        	</div>\r\n");
      out.write("	        </div>\r\n");
      out.write("			\r\n");
      out.write("	        <form>\r\n");
      out.write("				Filtrar videojuegos por proveedor: \r\n");
      out.write("				<select name=\"Proveedor\" class=\"form-select\" id=\"selectprov\">\r\n");
      out.write("					<option value=\"\" disabled>Selecciona un proveedor</option>\r\n");
      out.write("					<option value=\"Todos\" selected>Todos</option>\r\n");
      out.write("					");

						ResultSet rsProv = null;
						try {
							rsProv = Proveedor.getProveedores();
							
							while(rsProv.next())
							{
      out.write("\r\n");
      out.write("							<option value=\"");
      out.print( rsProv.getInt("cve_prov") );
      out.write('"');
      out.write('>');
      out.print( rsProv.getInt("cve_prov") );
      out.write(' ');
      out.write('-');
      out.write(' ');
      out.print( rsProv.getString("nom_prov") );
      out.write("</option>\r\n");
      out.write("							");
}
						}
						catch (SQLException e)
						{
							System.out.println("Error al acceder a la Base de Datos " +e.getMessage());
						}
						finally
						{
							if(rsProv != null) rsProv.close();
						}	
					
      out.write("\r\n");
      out.write("				</select>\r\n");
      out.write("			</form>\r\n");
      out.write("	        \r\n");
      out.write("			<table id=\"dtBasicExample\" class=\"table table-striped mt-4 mb-5\">\r\n");
      out.write("	        	<thead>\r\n");
      out.write("	            	<tr>\r\n");
      out.write("	              		<th>ID</th>\r\n");
      out.write("	              		<th>Nombre</th>\r\n");
      out.write("	              		<th>Precio</th>\r\n");
      out.write("	              		<th>Cve Prov</th>\r\n");
      out.write("	              		<th>Inventario</th>\r\n");
      out.write("	            	</tr>\r\n");
      out.write("	          	</thead>\r\n");
      out.write("	          	<tbody>	\r\n");
      out.write("	          		\r\n");
      out.write("	          		");
 
						ResultSet rsVid = null;
						try {
							rsVid = Videojuego.getVideojuegos();
							
							while(rsVid.next())
							{
      out.write("\r\n");
      out.write("								<tr>\r\n");
      out.write("									<th>");
      out.print( rsVid.getInt("cve_vid") );
      out.write("</th>\r\n");
      out.write("									<td>");
      out.print( rsVid.getString("tit_vid") );
      out.write("</td>\r\n");
      out.write("									<td>");
      out.print( rsVid.getFloat("pre_vid") );
      out.write("</td>\r\n");
      out.write("									<td>");
      out.print( rsVid.getInt("cveprov_vid") );
      out.write("</td>\r\n");
      out.write("									<td>");
      out.print( rsVid.getInt("inv_vid") );
      out.write("</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("							");
}
						}
						catch (SQLException e)
						{
							System.out.println("Error al acceder a la Base de Datos" +e.getMessage());
						}
						finally
						{
							if(rsVid != null) rsVid.close();
						}	
					
      out.write("\r\n");
      out.write("	          	</tbody>\r\n");
      out.write("	        </table>\r\n");
      out.write("		</div>\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
